### DISCUSSION TITLE
`toml_edit` - Is there any way to edit a Inline table postamble?

### DISCUSSION THREAD

**Discussion by sylbeth** [toml-rs/toml#819] [Q&A]
I am trying to format my inline tables as follows:

```toml
key = {
    key = value,
    key = value
}
```

For now I achieved the following setting the key decor to prefix "\n    " suffix " ":

```toml
key = {
    key = value,
    key = value }
```

But I don't know that to change from here. The preamble only affects the start after the {, right? Is there nothing I can change for that space but the decor of the last entry?

**Comment by epage** [comment]
Note that multi-line inline tables are not supported in the [1.0.0 spec](https://toml.io/en/v1.0.0#inline-table) which is what we support.  The fact that you can create generate multi-line inline tables is being tracked in #267.

When the 1.1 spec is released and we support this case, the way to do it would be to add it as a suffix to the value.

**Reply by sylbeth** [reply]
So it would be what I said in any case, right? Finding the last and adding a suffix? I'll be waiting for that moment, then, my use case is very specific since I have to make sure Godot can deserialize it properly.

**Reply by sylbeth** [reply]
Also, another qustion, just to check, but I'm pretty sure I'm right, there is no way this is ever going to be okay in a TOML, right?

```toml
[libraries]

macos.debug = "res://bin/libgdexample.macos.template_debug.framework"
macos.release = "res://bin/libgdexample.macos.template_release.framework"
macos.debug.arm64 = "res://bin/libgdexample.linux.template_debug.arm64.so"
macos.release.arm64 = "res://bin/libgdexample.linux.template_release.arm64.so"
```

I hate somehow .gdextension being basically a TOML but it not having to be compliant to work.
