### ISSUE TITLE
Serialization of Datetime outputs a table instead of actual date

### ISSUE THREAD

**Issue by Yesterday17** [toml-rs/toml#333]
I'm using `toml-rs` and was trying to switch to `toml_edit`, but the result of serialized date was not valid.

### Code
```rust
// main.rs
use toml_edit::{Date, Datetime, easy::to_string};
use serde::Serialize;

#[derive(Serialize)]
struct Struct {
    date: Datetime,
}

fn main() {
    let toml = to_string(&Struct {
        date: Datetime {
            date: Some(Date {
                year: 2022,
                month: 1,
                day: 1,
            }),
            time: None,
            offset: None,
        }
    }).unwrap();
    assert_eq!(toml, "date = 2022-01-01");
}
```

```toml
# Cargo.toml
[package]
name = "reproduce"
version = "0.1.0"
edition = "2021"

[dependencies]
toml_edit = { version = "0.14.4", features = ["easy"] }
serde = "1.0"
```

### Expected
`date = 2022-01-01`

### Got
`date = { "$__toml_private_datetime" = "2022-01-01" }`
