### ISSUE TITLE
toml_edit::easy formatting differences from toml-rs

### ISSUE THREAD

**Issue by paul-hansen** [toml-rs/toml#354]
I tried using `toml_edit::easy` on one of my projects since it sounds like it will be the future according to https://github.com/toml-rs/toml/issues/340 and noticed that table like fields are treated differently in `toml_edit::easy`. (See examples below)

I'm wondering if this is this an intentional change or something that might be fixed before the migration? If intentional, could we add a way to configure it to use the old style?
I find the old style to be more readable, uses less characters, provides better diffs, and is less error prone when editing (don't have to worry about matching brackets as much etc.).

_toml_edit::easy::to_string_
```toml
name = "Tom"
metadata = { hair_color = "brown", "dog's name" = "Frodo" }
addresses = [{ id = 0, name = "Home", street = "123 Baker ST" }, { id = 1, name = "Office", street = "124 Baker ST" }]
```

_toml::to_string_
```toml
name = "Tom"

[metadata]
hair_color = "brown"
"dog's name" = "Frodo"

[[addresses]]
id = 0
name = "Home"
street = "123 Baker ST"

[[addresses]]
id = 1
name = "Office"
street = "124 Baker ST"
```

Code used for this

``` rust
use serde::Serialize;
use std::collections::HashMap;

#[derive(Serialize)]
pub struct Address {
    id: usize,
    name: String,
    street: String,
}

#[derive(Serialize)]
pub struct Person {
    name: String,
    metadata: HashMap<String, String>,
    addresses: Vec<Address>,
}

fn main() {
    let mut hm = HashMap::new();
    hm.insert("dog's name".into(), "Frodo".into());
    hm.insert("hair_color".into(), "brown".into());
    let person = Person {
        name: "Tom".to_string(),
        metadata: hm,
        addresses: vec![
            Address {
                id: 0,
                name: "Home".to_string(),
                street: "123 Baker ST".to_string(),
            },
            Address {
                id: 1,
                name: "Office".to_string(),
                street: "124 Baker ST".to_string(),
            },
        ],
    };

    println!("{}", toml::to_string(&person).unwrap());
    println!("---");
    println!("{}", toml_edit::easy::to_string(&person).unwrap());
}
```
