### ISSUE TITLE
Incompatibility between `toml` and `toml_edit::easy`

### ISSUE THREAD

**Issue by obsgolem** [toml-rs/toml#421]
The following test crashes:

```rust
use globset::Glob;
use serde::Deserialize;

#[derive(Deserialize)]
struct Test {
    foo: Vec<Glob>,
}

fn main() {
    // let test = "\"test\"";
    // let tmp = toml::de::from_str::<&str>(test).unwrap();
    // let tmp2 = toml_edit::easy::from_str::<&str>(test).unwrap();

    let text = r#"foo=["hello", "world"]"#;
    let tmp = toml::de::from_str::<Test>(text).unwrap();
    let tmp2 = toml_edit::easy::from_str::<Test>(text).unwrap();
}
```

With the following `Cargo.toml` file

```toml
[package]
edition = "2021"
name = "toml_repro"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globset = {version = "0.4.10", features = ["serde1"]}
serde = "1.0.152"
toml = "0.5"
toml_edit = {version = "0.17.1", features = ["easy", "serde"]}
```

The crash occurs on line 16, showing that while `toml` can successfully deserialize into the `Glob`, `toml_edit::easy` cannot. This appears to be due to the implementation of `Deserialize` for `Glob` using `&str::deserialize` as opposed to `String::deserialize`.

Another incompatibility I found while trying to reproduce the issue: if you uncomment the commented lines in the code above, you will get a compiler error on line 12 but not on line 11.
