### ISSUE TITLE
Serializing mixed arrays results in invalid output

### ISSUE THREAD

**Issue by jcaesar** [toml-rs/toml#423]
Serializing mixed sequences like `[42, {"x": false}]` `[{"x": false}, 42]` (JSON) yields to invalid TOML being written:
```toml
[42
[[]]
x = false
]
```
```toml
[[]]
x = false
, 42
```
[Playground](play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ece7d97e69f43eb9f4c86afb95d2da70)

(I don't depend on this being handled correctly (error out?) - i.e. it would be low priority for me. I figure it's better I reported it anyway.)
