### ISSUE TITLE
TOML parse error: Invalid table header: Duplicate key

### ISSUE THREAD

**Issue by messense** [toml-rs/toml#439]
```toml
# pyproject.toml

[tool.hatch]
version.source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"
```

Both `toml` and `toml_edit` fail to parse it:

```rust
// toml
Err(
    Error {
        inner: ErrorInner {
            kind: Custom,
            line: Some(
                5,
            ),
            col: 0,
            at: Some(
                55,
            ),
            message: "duplicate key: `version`",
            key: [
                "tool",
                "hatch",
            ],
        },
    },
)

// toml_edit
Err(
    TomlError {
        message: "TOML parse error at line 6, column 1\n  |\n6 | [tool.hatch.version.raw-options]\n  | ^\nInvalid table header\nDuplicate key `version`\n",
        line_col: Some(
            (
                5,
                0,
            ),
        ),
    },
)
```

while the Python `tomllib` has no issue with it

```bash
Python 3.11.0 (main, Oct 25 2022, 16:25:24) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tomllib as toml
>>> s = '''# pyproject.toml
...
... [tool.hatch]
... version.source = "vcs"
...
... [tool.hatch.version.raw-options]
... local_scheme = "no-local-version"'''
>>> toml.loads(s)
{'tool': {'hatch': {'version': {'source': 'vcs', 'raw-options': {'local_scheme': 'no-local-version'}}}}}
```

[Rust Explorer Playground](https://www.rustexplorer.com/b/vthrz3)

See also https://github.com/charliermarsh/ruff/issues/1894

**Comment by epage** [comment]
Your TOML sample looks similar to this section in the TOML spec
```toml
[fruit]
apple.color = "red"
apple.taste.sweet = true

# [fruit.apple]  # INVALID
# [fruit.apple.taste]  # INVALID

[fruit.apple.texture]  # you can add sub-tables
smooth = true
```

with the accompanying rule being

> The [table] form can, however, be used to define sub-tables within tables defined via dotted keys.
