### ISSUE TITLE
Serializing Vec of arrays

### ISSUE THREAD

**Issue by marshallwalker** [toml-rs/toml#483]
Currently serializing a vec of arrays results in incorrect toml

Input:
```json
{
  "example": [
    [
      {
        "oof": 1
      }
    ]
  ]
}
```

Output:
```toml
[[example]]
oof = 1
,
]
```
