### ISSUE TITLE
Redefined tables are allowed when dotted tables exist.

### ISSUE THREAD

**Issue by ehuss** [toml-rs/toml#509]
The following TOML:

```toml
[dependencies.foo]
version = "0.16"

[dependencies]
libc = "0.2"

[dependencies]
rand = "0.3.14"
```

seems to parse by the new `toml` implementation when it probably shouldn't. The `[dependencies]` table is defined twice, which goes against the spec per:

> Like keys, you cannot define a table more than once. Doing so is invalid.

This was previously rejected in toml 0.5.

Using toml 0.7.1
