### ISSUE TITLE
How to read file without quoted fields?

### ISSUE THREAD

**Issue by lcmgh** [toml-rs/toml#522]
While implementing a tool that reads the current aws config I noticed I have an actual invalid toml file as fields are not escaped with quotes. However the official aws cli can still read from it.

Can I work around that with this library in a way that unquoted fields are parsed as string?

```toml
[profile abc]
output=json
region=eu-central-1
```
