### ISSUE TITLE
Incorrect roundtripping when table sources are mixed

### ISSUE THREAD

**Issue by epage** [toml-rs/toml#527]
```toml
[package]
metadata.msrv = "1.65.0"

[[package.metadata.release.pre-release-replacements]]
```

When loading and then writing the above, the array of tables if lost

From crate-ci/cargo-release#653
