### ISSUE TITLE
Feature request: Serializing with comments

### ISSUE THREAD

**Issue by fxdave** [toml-rs/toml#541]
Thanks for the library. I use it in my project (https://github.com/fxdave/vonal-rust).
I'd like to have an option to generate comments with the keys.

## Why
I create the config schema dynamically on the fly. I want to give an option to add comments to the keys. So I only need serialization. Deserialization of comments is not needed for me.

## An idea for implementing it

I can imagine a `Value::WithComment { value: Value, comment: String }` variant.
For example:
```rust
table.insert("something", Value::WithComment {
    value: Value::String("some value")
    comment: String::from("Some comment")
})

// ...

table.to_string() // this would include the comment
```

### Alternative syntax
```rust
Value::Boolean(true).with_comment("Some comment")
```

### Comment placement
Always above the value.

```toml
# foo comment
foo = ""

# bar comment
[bar]
# baz comment
baz=false
# handling
# multiline
# strings
# would be nice 
lorem = "ipsum"
```
