### ISSUE TITLE
Support for subtable name formatting to match Cargo.toml's Rust-like #[cfg] syntax

### ISSUE THREAD

**Issue by diliop** [toml-rs/toml#552]
Using `toml_edit`, I'm trying to output something like this:
```toml
[target.'cfg(target_os = "windows")'.dependencies]
libc = "0.2.139"
```
but when I run this:
```rust
let key = r#"'cfg(target_os = "windows")'"#;
let mut d = Document::new();
d["target"] = table();
d["target"].as_table_mut().unwrap().set_dotted(true);
d["target"][key] = table();
d["target"][key].as_table_mut().unwrap().set_dotted(true);
d["target"][key]["dependencies"] = table();
d["target"][key]["dependencies"]["libc"] = value("0.2.139");
println!("{}", d);
```
I get this instead:
```toml
[target."'cfg(target_os = \"windows\")'".dependencies]
libc = "0.2.139"
```
My guess is I'm doing something wrong but I haven't figured out what exactly. Any help would be greatly appreciated!
