### ISSUE TITLE
Incorrect span for unknown field error

### ISSUE THREAD

**Issue by nissaofthesea** [toml-rs/toml#593]
I have an issue in a [larger project](https://crates.io/crates/smolbar) where `toml` sometimes reports incorrect spans for missing fields declared at the top level.
Below is a minimal recreation of what I think is the same issue.

Cargo.toml:

```toml
[package]
name = "toml-span-bug"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.178", default-features = false, features = ["derive"] }
toml = { version = "0.7.6", default-features = false, features = ["parse"] }
```

main.rs:

```rust
use serde::Deserialize;
use toml;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    pub a: i32,
    #[serde(flatten)]
    pub b: B,
}

#[derive(Deserialize)]
pub struct B {}

fn main() {
    match toml::from_str::<Config>(
        r#"a = 1
unknown = 1"#,
    ) {
        Ok(_) => {}
        Err(err) => {
            println!("{err}");
        }
    }
}
```

Running this gives the following output:

```console
$ cargo run
TOML parse error at line 1, column 1
  |
1 | a = 1
  | ^^^^^
unknown field `unknown`
```

I would expect the following span instead:

```
TOML parse error at line 2, column 1
  |
2 | unknown = 1
  | ^^^^^^^^^^^
unknown field `unknown`
```

Interestingly, the span stays the same if I add a newline at the top of the source, so it's not tied to the field `a`.

```diff
17c17,18
<         r#"a = 1
---
>         r#"
> a = 1
```

```console
$ cargo run
TOML parse error at line 1, column 1
  |
1 | 
  | ^
unknown field `unknown`
```
