### ISSUE TITLE
`toml_edit` produces invalid TOML

### ISSUE THREAD

**Issue by messense** [toml-rs/toml#594]
See the reproduction here: https://github.com/messense/toml-edit-repro, `cargo run` outputs

```toml
[dependencies]
polars-error = { version = "0.32.0", path = "../polars-error" }
atoi = { workspace = true, optional = true }

[dependencies.
arrow ]
package = "arrow2"
git = "https://github.com/jorgecarleitao/arrow2"
# git = "https://github.com/ritchie46/arrow2"
rev = "9beabec8cfb5502582d31ab898fdd36e7af0873c"
# path = "../arrow2"
# branch = "duration_json"
version = "0.17.2"
default-features = false
features = [
  "compute_aggregate",
  "compute_arithmetics",
  "compute_boolean",
  "compute_boolean_kleene",
  "compute_cast",
  "compute_comparison",
  "compute_concatenate",
  "compute_filter",
  "compute_if_then_else",
]
```

the

```
[dependencies.
arrow ]
```

part is invalid TOML.

See also:

- https://github.com/PyO3/maturin/issues/1732
- https://github.com/pola-rs/polars/issues/10366
