### ISSUE TITLE
how to auto convert this style toml expression

### ISSUE THREAD

**Issue by baoyachi** [toml-rs/toml#599]
I expect this style toml expression:
```toml
[x_gen]
speed = 1000
samples = [
    { file = "./x.log", ratio =0.1 },
    { file = "./x.log", ratio =0.1 },
    { file = "./x.log", ratio =0.1 },
]
```
But, toml auto gen this style .
```toml
[x_gen]
speed = 1000

[[x_gen.samples]]
file = "./x.log"
ratio = 0.1

[[x_gen.samples]]
file = "./x.log"
ratio = 0.1

[[x_gen.samples]]
file = "./x.log"
ratio = 0.1
```

So,how to solve it.

Full example code:
<details>
<summary>Click to expand and see the code</summary>

```rust
use serde_json::json;

fn main() {
    let s = r#"
[x_gen]
speed = 1000
samples = [
    { file = "./x.log", ratio =0.1 },
    { file = "./x.log", ratio =0.1 },
    { file = "./x.log", ratio =0.1 },
]

    "#;


    let x: serde_json::Value = toml::from_str(s).unwrap();
    assert_eq!(x, json!({
        "x_gen":{
            "speed":1000,
            "samples":[
                {"file":"./x.log","ratio":0.1},
                {"file":"./x.log","ratio":0.1},
                {"file":"./x.log","ratio":0.1},
            ]
        }
    }));


    let expect = r#"
[x_gen]
speed = 1000

[[x_gen.samples]]
file = "./x.log"
ratio = 0.1

[[x_gen.samples]]
file = "./x.log"
ratio = 0.1

[[x_gen.samples]]
file = "./x.log"
ratio = 0.1
"#;
    let string = toml::to_string(&x).unwrap();
    assert_eq!(string.trim(), expect.trim())
}
```
</details>
