### ISSUE TITLE
`serde::Serialize` does not work with valid utf-8 encoded `OsString`

### ISSUE THREAD

**Issue by hn275** [toml-rs/toml#784]
I know `OsString` may or may not be utf-8, which could be a violation to toml format from the [spec](https://toml.io/en/v1.0.0-rc.3#spec). 

I can serialize it with valid utf-8 characters, but the output is not what I expected. 

```rs
use std::{ffi::OsString, str::FromStr};

#[derive(serde::Serialize)]
struct FooOsString {
    bar: OsString,
}

fn main() {
    let foo_os = FooOsString {
        bar: OsString::from_str("foo").expect("invalid encoding"),
    };
    let encoding_os = toml::to_string(&foo_os).expect("failed to serialize to toml string");

    println!("{}", encoding_os);

    /* output:

    [bar]
    Unix = [102, 111, 111]

    */
}

```

and here is my dependency list in `Cargo.toml`

```toml
[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"

```
