### ISSUE TITLE
How to avoid dotted subtables entirely?

### ISSUE THREAD

**Issue by fosskers** [toml-rs/toml#809]
Hi there. Currently naive calls to `to_string_pretty` yield output like:
```toml
[[foo]]
a = "a"

[foo.bar]
b = "b"
```
but I'd like it to output:
```toml
[[foo]]
a = "a"
bar = { b = "b" }
```
How can I accomplish this? I spent some time experimenting with `DocumentMut` but was unsuccessful. `set_dotted` seems like it might be what I want, but in practice it didn't appear to be. Am I overlooking something obvious?

Thank you.
